FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV CHOKIDAR_USEPOLLING=1
ENV WATCHPACK_POLLING=true
ENV NODE_ENV=development

EXPOSE 5173
CMD ["sh", "-c", "npm run dev -- --host 0.0.0.0 --port 5173"]
